//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int P_Id { get; set; }
        public string P_Name { get; set; }
        public string P_Cost { get; set; }
        public string P_Description { get; set; }
        public Nullable<int> P_Active { get; set; }
        public int C_Id { get; set; }
    }
}
